FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["FitnessLeaderboard.Api/FitnessLeaderboard.Api.csproj", "fitness-leaderboard/"]
RUN dotnet restore "fitness-leaderboard/FitnessLeaderboard.Api.csproj"
COPY . .
WORKDIR "/src/fitness-leaderboard"
RUN dotnet build "FitnessLeaderboard.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish ".FitnessLeaderboard.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FitnessLeaderboard.Api.dll"]
